### ISSUE TITLE
This quiz is not in the right spot

### ISSUE THREAD

**Issue by howardemilya** [learn-co-curriculum/js-dom-and-events-dom-quiz#1]
It has literally nothing to do with the previous 13 lessons regarding the DOM. Almost every question is about material that was not covered whatsoever in the DOM section. It just makes no sense.

**Comment by drakeltheryuujin** [comment]
Hi @howardemilya,

Thank you for your feedback. Our next major release of this section of curriculum is targeted for delivery in the first half of 2019, and should remedy this issue. Thank you for your contribution!
